# Generated by Django 5.0.7 on 2024-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deletepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletePost',
        ),
    ]
